apiVersion: apps/v1
kind: Deployment
metadata:
  name: fl-pubs
  namespace: fl
  labels:
    app: fl-pubs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fl-pubs
  template:
    metadata:
      labels:
        app: fl-pubs
    spec:
      serviceAccountName: fl-svc-account
      restartPolicy: "Always"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: fl
                    operator: In
                    values:
                      - "core"
      containers:
        - name: pubs
          image: "docker.io/mattrent/pubs-flask:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: fl-pubs-service
  namespace: fl
  labels:
    app: fl-pubs
spec:
  type: ClusterIP
  selector:
    app: fl-pubs
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
